version: "3"

volumes:
  db_data:
  mail_data:

services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
