name: commit

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/actions/test.yml
  deploy:
    uses: ./.github/workflows/actions/deploy.yml
    with:
      app-name: ${{ env.APP_NAME }}
    secrets: inherit
