name: commit

on: 
  push:
    branches:
      - main

jobs:
  test-prod:
    uses: ./.github/workflows/_test.yml
  mutation-test-prod:
    uses: ./.github/workflows/_mutation-test.yml
    with:
      s3-baseurl: s3://soshal-mutation-test/main
    secrets: inherit
  deploy-prod:
    uses: ./.github/workflows/_deploy.yml
    needs: test-prod
    with:
      app-name: soshal
      docker-name: soshal:latest
    secrets: inherit
