name: commit

on:
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/_test.yml
  deploy:
    uses: ./.github/workflows/_deploy.yml
    needs: test
    with:
      app-name: soshal
    secrets: inherit
