name: deploy

on:
  push:
    branches: main
  pull_request:

env:
  DOCKER_IMAGE: ghcr.io/mkizka/soshal:pr${{ github.event.pull_request.number }}
  CAPROVER_URL: paas.mkizka.dev
  APP_NAME: pr${{ github.event.pull_request.number }}-soshal
  APP_DOMAIN: pr${{ github.event.pull_request.number }}-soshal.mkizka.dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mkizka
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }},mode=max
      - name: Create new app
        continue-on-error: true
        run: |
          npx caprover api \
            -m POST \
            -t /user/apps/appDefinitions/register \
            -d '{"appName":"${{ env.APP_NAME }}","hasPersistentData":false}' \
            -u ${{ env.CAPROVER_URL }} \
            -p ${{ secrets.CAPROVER_PASSWORD }}
      - name: Set custom domain
        continue-on-error: true
        run: |
          npx caprover api \
            -m POST \
            -t /user/apps/appDefinitions/customdomain \
            -d '{"appName":"pr1-soshal","customDomain":"${{ env.APP_DOMAIN }}"}' \
            -u ${{ env.CAPROVER_URL }} \
            -p ${{ secrets.CAPROVER_PASSWORD }}
      - name: Set environment variables
        run: |
          envVars=$(jq -cn \
            --arg DATABASE_URL "${{ secrets.DATABASE_URL }}/${{ env.APP_NAME }}" \
            --arg NEXTAUTH_SECRET "${{ secrets.NEXTAUTH_SECRET }}" \
            --arg NEXTAUTH_URL https://${{ env.APP_DOMAIN }} \
            --arg EMAIL_SERVER_USER "${{ secrets.EMAIL_SERVER_USER }}" \
            --arg EMAIL_SERVER_PASS "${{ secrets.EMAIL_SERVER_PASS }}" \
            --arg EMAIL_SERVER_HOST in-v3.mailjet.com \
            --arg EMAIL_SERVER_PORT 587 \
            --arg EMAIL_FROM mail@test.mkizka.dev \
            '$ARGS.named | to_entries')
          data=$(jq -cn \
            --arg appName ${{ env.APP_NAME }} \
            --arg instanceCount 1 \
            --arg containerHttpPort 3000 \
            --arg envVars "$envVars" \
            '$ARGS.named')
          npx caprover api \
            -m POST \
            -t /user/apps/appDefinitions/update \
            -d "$data" \
            -u ${{ env.CAPROVER_URL }} \
            -p ${{ secrets.CAPROVER_PASSWORD }}
      - name: Deploy app
        run: |
          npx caprover deploy \
            -a ${{ env.APP_NAME }} \
            -i ${{ env.DOCKER_IMAGE }} \
            -u ${{ env.CAPROVER_URL }} \
            -p ${{ secrets.CAPROVER_PASSWORD }}
