name: pr

on:
  pull_request:

env:
  APP_NAME: pr${{ github.event.pull_request.number }}-soshal

jobs:
  test-pr:
    uses: ./.github/workflows/_test.yml
  deploy-pr:
    uses: ./.github/workflows/_deploy.yml
    needs: test-pr
    with:
      app-name: ${{ env.APP_NAME }}
    secrets: inherit
  comment-pr:
    runs-on: ubuntu-latest
    needs: deploy-pr
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            確認環境が作成されました
            :rocket: https://${{ env.APP_NAME }}.mkizka.dev
          comment_tag: link
