name: pr

on:
  pull_request:

jobs:
  test-pr:
    uses: ./.github/workflows/_test.yml
  # deploy-pr:
  #   uses: ./.github/workflows/_deploy.yml
  #   needs: test-pr
  #   with:
  #     app-name: pr${{ github.event.pull_request.number }}-soshal
  #     docker-name: soshal:pr${{ github.event.pull_request.number }}
  #   secrets: inherit
