name: pr

on:
  pull_request:

env:
  APP_NAME: pr${{ github.event.pull_request.number }}-soshal

jobs:
  test:
    uses: ./.github/workflows/actions/test.yml
  deploy:
    uses: ./.github/workflows/actions/deploy.yml
    with:
      app-name: ${{ env.APP_NAME }}
    secrets: inherit
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            確認環境が作成されました
            :rocket: https://${{ env.APP_NAME }}.mkizka.dev
          comment_tag: link
